module.exports = {
    apps : [
      {
        name: 'GALABUSD',
        cmd: '/home/enrique/pycryptobot/pycryptobot.py',
        args:  ['--exchange=binance', '--market=GALABUSD', '--buymaxsize=300'],
        autorestart: false,
        wait_ready: true,
        watch: true,
        instances: 1,
        restart_delay: 30000,
        max_restarts: 5,
        max_memory_restart: '256M',
        interpreter: '/home/enrique/pycryptobot/venv/bin/python',
      },
      {
        name: 'ICXBUSD',
        cmd: '/home/enrique/pycryptobot/pycryptobot.py',
        args:  ['--exchange=binance', '--market=ICXBUSD', '--buymaxsize=300'],
        autorestart: false,
        wait_ready: true,
        watch: true,
        instances: 1,
        restart_delay: 30000,
        max_restarts: 5,
        max_memory_restart: '256M',
        interpreter: '/home/enrique/pycryptobot/venv/bin/python',
      },
      {
        name: 'FILBUSD',
        cmd: '/home/enrique/pycryptobot/pycryptobot.py',
        args:  ['--exchange=binance', '--market=FILBUSD', '--buymaxsize=300'],
        autorestart: false,
        wait_ready: true,
        watch: true,
        instances: 1,
        restart_delay: 30000,
        max_restarts: 5,
        max_memory_restart: '256M',
        interpreter: '/home/enrique/pycryptobot/venv/bin/python',
      },
      {
        name: 'GRTBUSD',
        cmd: '/home/enrique/pycryptobot/pycryptobot.py',
        args:  ['--exchange=binance', '--market=GRTBUSD', '--buymaxsize=300'],
        autorestart: false,
        wait_ready: true,
        watch: true,
        instances: 1,
        restart_delay: 30000,
        max_restarts: 5,
        max_memory_restart: '256M',
        interpreter: '/home/enrique/pycryptobot/venv/bin/python',
      }
  ]};  